In [1]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y ,x*y,  x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x = torch.arange(4)
x[3]

tensor(3)

In [3]:
len(x)

4

In [4]:
x.shape

torch.Size([4])

In [5]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [8]:
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0 , A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [9]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [10]:
A.sum(axis=[0, 1])

tensor(190.)

In [11]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [12]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [13]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A


tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [14]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [15]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [16]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

点积是相同位置的按元素乘积的和
我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [17]:
torch.sum(x * y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，其第i个元素是点积$a^⊤_{i}x$

In [18]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单地执行m
次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵

In [19]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根：

In [20]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L1范数，它表示为向量元素的绝对值之和：

In [21]:
torch.abs(u).sum()

tensor(7.)

矩阵 的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素平方和的平方根：

In [22]:
torch.norm(torch.ones((4, 9)))

tensor(6.)